### ISSUE TITLE
Getting Status KeyError when getting health information

### ISSUE THREAD

**Issue by rdbreak** [lgaggini/dell_hw_health#2]
```
Traceback (most recent call last):
  File "dell_hw_check.py", line 404, in <module>
    get_fan_information()
  File "dell_hw_check.py", line 177, in get_fan_information
    status = get_status(data)
  File "dell_hw_check.py", line 46, in get_status
    return data[u'Status']['Health']
KeyError: 'Status'

Traceback (most recent call last):
  File "dell_hw_check.py", line 406, in <module>
    get_ps_information()
  File "dell_hw_check.py", line 211, in get_ps_information
    status = get_status(data)
  File "dell_hw_check.py", line 46, in get_status
    return data[u'Status']['Health']
KeyError: 'Status'
```

Let me know if there is any other information I can provide to help fix this issue.

**Comment by lgaggini** [comment]
Hi,

you could try to add a log/print of the `data` object before to try to access it so we can inspect it.
I see there is a little gap between the line numbers of the original script and your traceback. Are there some code changes in place?

Thank you for the report.

**Comment by rdbreak** [comment]
Thank you!
